// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HEADER_STD_MSGS_H_
#define FLATBUFFERS_GENERATED_HEADER_STD_MSGS_H_

#include "flatbuffers/flatbuffers.h"

namespace std_msgs {

struct Header;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Header FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t msgTypeId_;
  uint32_t msgSize_;

 public:
  Header()
      : msgTypeId_(0),
        msgSize_(0) {
  }
  Header(uint32_t _msgTypeId, uint32_t _msgSize)
      : msgTypeId_(flatbuffers::EndianScalar(_msgTypeId)),
        msgSize_(flatbuffers::EndianScalar(_msgSize)) {
  }
  uint32_t msgTypeId() const {
    return flatbuffers::EndianScalar(msgTypeId_);
  }
  uint32_t msgSize() const {
    return flatbuffers::EndianScalar(msgSize_);
  }
};
FLATBUFFERS_STRUCT_END(Header, 8);

}  // namespace std_msgs

#endif  // FLATBUFFERS_GENERATED_HEADER_STD_MSGS_H_
